# -*- coding: utf-8 -*-
"""Rock or Mine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pjtWkmuOUaYN581VLA1CC-f2imglW1OH
"""

#importing dependencies
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

sonar_data = pd.read_csv('/content/sonar data.csv',header=None)

sonar_data.tail()

sonar_data.shape

sonar_data.describe()

sonar_data[60].value_counts()

X = sonar_data.drop(columns=60,axis=1)
Y = sonar_data[60]

print(X)

print(Y)

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.1,stratify=Y,random_state=3)

print(X.shape,X_test.shape,X_train.shape)

model = LogisticRegression()

model.fit(X_train,Y_train)

X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

print("Accuracy on training data: ",training_data_accuracy)

X_test_prediction = model.predict(X_test)
test_data_accuracy =accuracy_score(X_test_prediction,Y_test)

print("Accuracy on testing data: ",test_data_accuracy)

input_data = (0.0200 ,0.0371  ,0.0428  ,0.0207  ,0.0954  ,0.0986  ,0.1539  ,0.1601,0.3109,0.2111,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084 ,0.0090,0.0032,0.0200  ,0.0371  ,0.0428  ,0.0207  ,0.0954  ,0.0986  ,0.1539  ,0.1601  ,0.3109,0.0200 ,0.0371  ,0.0428  ,0.0207  ,0.0954 ,0.0200 ,0.0371  ,0.0428  ,0.0207  ,0.0954 ,0.0200 ,0.0371  ,0.0428  ,0.0207  ,0.0954 ,0.0200 ,0.0371  ,0.0428  ,0.0207  ,0.0954 ,0.0200 ,0.0371  ,0.0428  ,0.0207  ,0.0954 ,0.0200 ,0.0371  ,0.0428  ,0.0207  ,0.0954,0.0954)

input_data_as_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
if(prediction[0]=="R"):
  print("It is a rock")
else:
  print("It is a Mine")

